// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRRSbE2EyM7RPU5BsFseL2NcxD0SupVsg',
    appId: '1:572211571182:web:20e1cd6ba83275eca486ff',
    messagingSenderId: '572211571182',
    projectId: 'pancito-app',
    authDomain: 'pancito-app.firebaseapp.com',
    storageBucket: 'pancito-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1I8bK1_w_QQ3zu1ZsgIOpE5maWUIcLxg',
    appId: '1:572211571182:android:5ffb2723c821909ba486ff',
    messagingSenderId: '572211571182',
    projectId: 'pancito-app',
    storageBucket: 'pancito-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApFVS5BNlFq9049Dv6UwJpRAKMUV4xOV8',
    appId: '1:572211571182:ios:62627ce68bbd76f1a486ff',
    messagingSenderId: '572211571182',
    projectId: 'pancito-app',
    storageBucket: 'pancito-app.firebasestorage.app',
    iosBundleId: 'com.example.pancitoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApFVS5BNlFq9049Dv6UwJpRAKMUV4xOV8',
    appId: '1:572211571182:ios:62627ce68bbd76f1a486ff',
    messagingSenderId: '572211571182',
    projectId: 'pancito-app',
    storageBucket: 'pancito-app.firebasestorage.app',
    iosBundleId: 'com.example.pancitoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRRSbE2EyM7RPU5BsFseL2NcxD0SupVsg',
    appId: '1:572211571182:web:b0cf6665cf1d122aa486ff',
    messagingSenderId: '572211571182',
    projectId: 'pancito-app',
    authDomain: 'pancito-app.firebaseapp.com',
    storageBucket: 'pancito-app.firebasestorage.app',
  );
}
